In [1]:
import pandas
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [2]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)

In [3]:
# X = Features and y = labels

In [4]:
print(f'Type of features array: { type(X)}')

# sepal_length, sepal_width, petal_length, petal_width

print(f'{X[:5]}')

Type of features array: <class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [5]:
print(f'Type of label array: {type(y)}')

# Species
print(f'{y[:5]}')

Type of label array: <class 'numpy.ndarray'>
[0 0 0 0 0]


In [6]:
#shuffle the data before training

In [7]:
from sklearn.model_selection import train_test_split

# 80% Train, 10% Validation, 10% Test

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X_test, y_test=0.5, random_state=42)

NameError: name 'test_size' is not defined

In [9]:
from sklearn.naive_bayes import GaussianNB

nb_model = GaussianNB (var_smoothing=10)